name: aoc
version: 0.1.0.0
github: "githubuser/aoc"
license: BSD-3-Clause
author: "Author name here"
maintainer: "example@example.com"
copyright: "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/aoc#readme>

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - lens
  - comonad
  - parsec
  - hmatrix
  - MemoTrie
  - monad-loops
  - containers
  - heap
  - array
  - monoidal-containers
  - mtl
  - recursion-schemes
  - deepseq
  - sized-grid
  - vector-space
  - bytestring
  - constraints
  - vector
  - linear
  - vector-algorithms
  - split

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  aoc-2015-01:
    main: src/2015/01.hs
  aoc-2015-02:
    main: src/2015/02.hs
  aoc-2024-01:
    main: src/2024/01.hs
  aoc-2024-02:
    main: src/2024/02.hs
  aoc-2024-03:
    main: src/2024/03.hs
  aoc-2024-04:
    main: src/2024/04.hs
  aoc-2025-01:
    main: src/2025/01.hs
  aoc-2025-02:
    main: src/2025/02.hs
  aoc-2025-03:
    main: src/2025/03.hs
  aoc-2025-04:
    main: src/2025/04.hs
  aoc-2025-05:
    main: src/2025/05.hs
  aoc-2025-06:
    main: src/2025/06.hs
  aoc-2025-07:
    main: src/2025/07.hs
  aoc-2025-08:
    main: src/2025/08.hs
  aoc-2025-09:
    main: src/2025/09.hs
  aoc-2025-10:
    main: src/2025/10.hs
  aoc-2025-11:
    main: src/2025/11.hs
  aoc-2025-12:
    main: src/2025/12.hs
